jaffle_shop:
  outputs:
    dev:
      dataset: jaffle_shop
      keyfile: C:\Users\alfre\.gcp\dbt.json
      location: US
      method: service-account
      project: sharp-harbor-411301
      threads: 4
      type: bigquery
  target: dev
