jaffle_shop:
  outputs:
    dev:
      dataset: dbt_core_dev
      keyfile: C:\Users\alfre\.gcp\dbt.json
      location: australia-southeast1
      method: service-account
      project: sharp-harbor-411301
      threads: 4
      type: bigquery
    prod:
      dataset: dbt_core_prod
      keyfile: C:\Users\alfre\.gcp\dbt.json
      location: australia-southeast1
      method: service-account
      project: sharp-harbor-411301
      threads: 4
      type: bigquery
  target: dev
